spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: aeisel
    password: toor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-plateform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
